import { useState } from 'react';

const cities = [
	'Alaminos',
	'Antipolo',
	'Bacolod',
	'Baguio',
	'Bais',
	'Batac',
	'Bayawan',
	'Bogo',
	'Borongan',
	'Butuan',
	'Cabadbaran',
	'Cadiz',
	'Calapan',
	'Calbayog',
	'Caloocan',
	'Candon',
	'Catbalogan',
	'Cauayan',
	'Cebu City',
	'Cotabato',
	'Dagupan',
	'Danao',
	'Dapitan',
	'Davao City',
	'Digos',
	'Dipolog',
	'Dumaguete',
	'Escalante',
	'General Santos',
	'Gingoog',
	'Guihulngan',
	'Himamaylan',
	'Ilagan',
	'Iligan',
	'Iloilo City',
	'Isabela',
	'Kabankalan',
	'Kidapawan',
	'Koronadal',
	'La Carlota',
	'Lamitan',
	'Laoag',
	'Lapu-Lapu',
	'Las Piñas',
	'Legazpi',
	'Ligao',
	'Lipa',
	'Lucena',
	'Maasin',
	'Makati',
	'Malabon',
	'Malaybalay',
	'Malolos',
	'Mandaluyong',
	'Mandaue',
	'Manila',
	'Marawi',
	'Marikina',
	'Masbate City',
	'Mati',
	'Meycauayan',
	'Minglanilla',
	'Muntinlupa',
	'Naga',
	'Navotas',
	'Olongapo',
	'Ormoc',
	'Oroquieta',
	'Ozamiz',
	'Pagadian',
	'Palayan',
	'Panabo',
	'Parañaque',
	'Pasay',
	'Pasig',
	'Puerto Princesa',
	'Quezon City',
	'Roxas',
	'Sagay',
	'San Carlos',
	'San Fernando',
	'San Jose del Monte',
	'San Juan',
	'San Pablo',
	'San Pedro',
	'Santa Rosa',
	'Santiago',
	'Silay',
	'Sipalay',
	'Sorsogon City',
	'Surigao',
	'Tabaco',
	'Tabuk',
	'Tacloban',
	'Tagaytay',
	'Tagbilaran',
	'Taguig',
	'Tagum',
	'Talisay',
	'Tanauan',
	'Tandag',
	'Tangub',
	'Tanjay',
	'Tarlac',
	'Toledo',
	'Trece Martires',
	'Tuguegarao',
	'Urdaneta',
	'Valencia',
	'Valenzuela',
	'Victorias',
	'Vigan',
	'Zamboanga City',
];

const provinces = [
	'Abra',
	'Agusan del Norte',
	'Agusan del Sur',
	'Aklan',
	'Albay',
	'Antique',
	'Apayao',
	'Aurora',
	'Basilan',
	'Bataan',
	'Batanes',
	'Batangas',
	'Benguet',
	'Biliran',
	'Bohol',
	'Bukidnon',
	'Bulacan',
	'Cagayan',
	'Camarines Norte',
	'Camarines Sur',
	'Camiguin',
	'Capiz',
	'Catanduanes',
	'Cavite',
	'Cebu',
	'Compostela Valley',
	'Cotabato',
	'Davao de Oro',
	'Davao del Norte',
	'Davao del Sur',
	'Davao Occidental',
	'Davao Oriental',
	'Dinagat Islands',
	'Eastern Samar',
	'Guimaras',
	'Ifugao',
	'Ilocos Norte',
	'Ilocos Sur',
	'Iloilo',
	'Isabela',
	'Kalinga',
	'La Union',
	'Laguna',
	'Lanao del Norte',
	'Lanao del Sur',
	'Leyte',
	'Maguindanao',
	'Marinduque',
	'Masbate',
	'Misamis Occidental',
	'Misamis Oriental',
	'Mountain Province',
	'Negros Occidental',
	'Negros Oriental',
	'Northern Samar',
	'Nueva Ecija',
	'Nueva Vizcaya',
	'Occidental Mindoro',
	'Oriental Mindoro',
	'Palawan',
	'Pampanga',
	'Pangasinan',
	'Quezon',
	'Quirino',
	'Rizal',
	'Romblon',
	'Samar',
	'Sarangani',
	'Siquijor',
	'Sorsogon',
	'South Cotabato',
	'Southern Leyte',
	'Sultan Kudarat',
	'Sulu',
	'Surigao del Norte',
	'Surigao del Sur',
	'Tarlac',
	'Tawi-Tawi',
	'Zambales',
	'Zamboanga del Norte',
	'Zamboanga del Sur',
	'Zamboanga Sibugay',
];

export const useCityOrProvinceFilter = () => {
	const [query, setQuery] = useState('');
	const [filteredCities, setFilteredCities] = useState([]);
	const [filteredProvinces, setFilteredProvinces] = useState([]);
	const [isDropdownVisible, setDropdownVisible] = useState(false);

	const handleInputChange = input => {
		const search = input.toLowerCase();
		setQuery(input);

		if (search.trim() !== '') {
			setFilteredCities(cities.filter(city => city.toLowerCase().includes(search)));
			setFilteredProvinces(provinces.filter(province => province.toLowerCase().includes(search)));
			setDropdownVisible(true);
		} else {
			setFilteredCities([]);
			setFilteredProvinces([]);
			setDropdownVisible(false);
		}
	};

	const handleSelect = selected => {
		setQuery(selected);
		setFilteredCities([]);
		setFilteredProvinces([]);
		setDropdownVisible(false);
	};

	return {
		query,
		filteredCities,
		filteredProvinces,
		isDropdownVisible,
		handleInputChange,
		handleSelect,
		setDropdownVisible,
	};
};
